name: tugas_besar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.0.1
  intl: ^0.18.1
  shared_preferences: ^2.1.0

  provider: ^6.0.0
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  pdf: ^3.10.0
  printing: ^5.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/images/BCA.png
    - assets/images/Mandiri.png
    - assets/images/BRI.png
    - assets/logoTravel2.png
    - assets/bus-picture.jpg
    - assets/promo1.jpg
    - assets/promo2.jpg
    - assets/promo3.jpg
    - assets/tips1.jpg
    - assets/tips2.jpg
    - assets/tips3.jpg
    - assets/default_profile.jpg