name: tugas_besar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  camera: ^0.10.5+2
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/images/BCA.png
    - assets/images/Mandiri.png
    - assets/images/BRI.png
    - assets/logoTravel.png
    - assets/bus-picture.jpg